name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch

jobs:
  build-pdf:
    runs-on: ubuntu-latest
                
            
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up TeX Live with additional packages
      - name: Set up TeX Live
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex  # Change to the path of your main .tex file
          compiler: xelatex  # Specify xelatex as the compiler
          pre_compile: |
            sudo apt-get update
            sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-science
            sudo apt-get install -y fonts-font-awesome
        
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: main.pdf
          path: main.pdf

      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          
      - name: Display structure of downloaded files
        run: ls -R
