name: Build LaTeX PDF

on:
  push:
    branches:
      - pdf  # Triggers on pushes to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch

jobs:
  build-pdf:
    permissions: write-all
    runs-on: ubuntu-lates
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up TeX Live with additional packages
      - name: Set up TeX Live
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex  # Change to the path of your main .tex file
          compiler: xelatex  # Specify xelatex as the compiler
          extra_packages: |
            tabularx
            titlesec
            geometry
            enumitem
            hyperref
            fancyhdr
            fontawesome5
            multicol
            fontenc
            academicons
            multirow
            # Add any other packages used in your .tex file
        
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: main.pdf
      
      - name: Push
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: pdf
          build_dir: pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
