name: Build LaTeX PDF

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch

jobs:
  build-pdf:
    runs-on: ubuntu-latest
                
            
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up TeX Live with additional packages
      - name: Set up TeX Live
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex  # Change to the path of your main .tex file
          compiler: xelatex  # Specify xelatex as the compiler
          extra_packages: |
            latexsym
            xcolor
            float
            ragged2e
            fullpage
            wrapfig
            lipsum
            tabularx
            titlesec
            geometry
            marvosym
            verbatim
            enumitem
            hyperref
            fancyhdr
            fontawesome5
            multicol
            graphicx
            fontenc
            academicons
            multirow
            tcolorbox
            # Add any other packages used in your .tex file

      # Upload the generated PDF as an artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: compiled-pdf
          path: main.pdf  # Change to the output PDF path
